In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv("C:\\Users\\Admin\\Downloads\\7 churn.csv")

In [4]:
df.head()
#df.shape,df.describe()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [5]:
columns_to_keep=['gender','SeniorCitizen','Partner','Dependents','tenure','PhoneService','MultipleLines','Contract','TotalCharges','Churn']

In [6]:
df=df[columns_to_keep]
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines        Contract TotalCharges Churn  
0  No phone service  Month-to-month        29.85    No  
1                No        One year       1889.5    No  
2                No  Month-to-month       108.15   Yes  
3  No phone service        One year      1840.75    No  
4                No  Month-to-month       151.65   Yes

In [7]:
categorical_columns=['Partner','Dependents','PhoneService','Churn']

In [8]:
df.isnull().sum()

gender           0
SeniorCitizen    0
Partner          0
Dependents       0
tenure           0
PhoneService     0
MultipleLines    0
Contract         0
TotalCharges     0
Churn            0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
categories=['gender','Partner','Dependents','PhoneService','MultipleLines','Contract','Churn']
for col in categories:
    df[col]=le.fit_transform(df[col])

In [10]:
df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  Contract TotalCharges  Churn  
0              1         0        29.85      0  
1              0         1       1889.5      0  
2              0         0       108.15      1  
3              1         1      1840.75      0  
4              0         0       151.65      1

In [11]:
x=df.drop('Churn',axis=1)
y=df['Churn']

In [12]:
x.head(),y.head()

(   gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
 0       0              0        1           0       1             0   
 1       1              0        0           0      34             1   
 2       1              0        0           0       2             1   
 3       1              0        0           0      45             0   
 4       0              0        0           0       2             1   
 
    MultipleLines  Contract TotalCharges  
 0              1         0        29.85  
 1              0         1       1889.5  
 2              0         0       108.15  
 3              1         1      1840.75  
 4              0         0       151.65  ,
 0    0
 1    0
 2    1
 3    0
 4    1
 Name: Churn, dtype: int32)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [14]:
x_train.shape,x_test.shape

((5634, 9), (1409, 9))

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   gender         7043 non-null   int32 
 1   SeniorCitizen  7043 non-null   int64 
 2   Partner        7043 non-null   int32 
 3   Dependents     7043 non-null   int32 
 4   tenure         7043 non-null   int64 
 5   PhoneService   7043 non-null   int32 
 6   MultipleLines  7043 non-null   int32 
 7   Contract       7043 non-null   int32 
 8   TotalCharges   7043 non-null   object
 9   Churn          7043 non-null   int32 
dtypes: int32(7), int64(2), object(1)
memory usage: 357.8+ KB


In [16]:
df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  Contract TotalCharges  Churn  
0              1         0        29.85      0  
1              0         1       1889.5      0  
2              0         0       108.15      1  
3              1         1      1840.75      0  
4              0         0       151.65      1

In [17]:
x_train['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')
x_test['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')

In [18]:
x_train['TotalCharges'].isnull().sum()

10

In [19]:
print(x_train.columns)
print(x_test.columns)

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'Contract', 'TotalCharges'],
      dtype='object')
Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'Contract', 'TotalCharges'],
      dtype='object')


In [20]:
x_train['TotalCharges'].fillna(x_train['TotalCharges'].mean(),inplace=True)
x_test['TotalCharges'].fillna(x_train['TotalCharges'].mean(),inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_11184\1080466123.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_train['TotalCharges'].fillna(x_train['TotalCharges'].mean(),inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_11184\1080466123.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always 

In [21]:
x_train['TotalCharges'].isnull().sum(),x_test['TotalCharges'].isnull().sum()

(0, 0)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train) 
x_test=scaler.fit_transform(x_test) 

In [23]:
x_train

array([[-1.02516569, -0.4377492 , -0.96957859, ..., -1.00053704,
         0.37290835, -0.42210502],
       [-1.02516569, -0.4377492 , -0.96957859, ...,  1.10833901,
         1.5775905 ,  1.25536015],
       [ 0.97545208, -0.4377492 ,  1.03137591, ...,  0.05390099,
        -0.83177379, -1.00299144],
       ...,
       [ 0.97545208, -0.4377492 ,  1.03137591, ..., -1.00053704,
        -0.83177379, -0.87799925],
       [ 0.97545208,  2.28441306, -0.96957859, ...,  1.10833901,
        -0.83177379, -0.48254445],
       [ 0.97545208, -0.4377492 , -0.96957859, ..., -1.00053704,
         0.37290835, -0.81110232]])

In [24]:
x_test

array([[-0.94946537, -0.44854601,  1.04724696, ...,  0.09805241,
        -0.81439391, -0.97678384],
       [ 1.05322431, -0.44854601, -0.95488461, ...,  1.15267717,
        -0.81439391, -0.55063861],
       [-0.94946537, -0.44854601,  1.04724696, ..., -0.95657236,
         1.54425156, -0.5351787 ],
       ...,
       [ 1.05322431, -0.44854601,  1.04724696, ..., -0.95657236,
         0.36492882, -0.84303919],
       [-0.94946537, -0.44854601,  1.04724696, ...,  0.09805241,
         1.54425156,  0.31057694],
       [ 1.05322431, -0.44854601, -0.95488461, ...,  0.09805241,
        -0.81439391, -0.97391115]])

In [25]:
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
lg.fit(x_train,y_train)
y_pred=lg.predict(x_test)

In [26]:
y_pred

array([1, 0, 0, ..., 0, 0, 1])

In [27]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.7778566359119943

In [28]:
import pickle
pickle.dump(lg, open("C:/Users/Admin/Downloads/7_logistic_model.pkl", "wb"))

In [29]:
dir

<function dir>

In [30]:
df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
0       0              0        1           0       1             0   
1       1              0        0           0      34             1   
2       1              0        0           0       2             1   
3       1              0        0           0      45             0   
4       0              0        0           0       2             1   

   MultipleLines  Contract TotalCharges  Churn  
0              1         0        29.85      0  
1              0         1       1889.5      0  
2              0         0       108.15      1  
3              1         1      1840.75      0  
4              0         0       151.65      1

In [36]:
import pandas as pd
gender = "Female"
SeniorCitizen =0
Partner = "No"
Dependents = "NO"
tenure = 2
PhoneService="Yes"
MultipleLines='No'
Contract="Month-to-month"
TotalCharges = 151.65
data={
        'gender':[gender],
        'Seniorcitizen':[SeniorCitizen],
        'Partner':[Partner],
        'Dependents':[Dependents],
        'tenure':[tenure],
        'Phoneservice':[PhoneService],
        'MultipleLines':[MultipleLines],
        'Contract':[Contract],
        'TotalCharges':[TotalCharges],
    }
    
df1=pd.DataFrame(data)

In [32]:
df1

gender  Seniorcitizen Partner Dependents  tenure Phoneservice  \
0  Female              0      No         NO       2          Yes   

  MultipleLines        Contract  TotalCharges  
0            No  Month-to-month        151.65

In [33]:
def predictive(gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges):
    data={
        'gender':[gender],
        'SeniorCitizen':[SeniorCitizen],
        'Partner':[Partner],
        'Dependents':[Dependents],
        'tenure':[tenure],
        'PhoneService':[PhoneService],
        'MultipleLines':[MultipleLines],
        'Contract':[Contract],
        'TotalCharges':[TotalCharges],
    }
    df1=pd.DataFrame(data)
    categorical_columns=['gender','Partner','Dependents','PhoneService','MultipleLines','Contract']
    for col in categorical_columns:
        df1[col]=le.fit_transform(df1[col])
    df1=scaler.fit_transform(df1)
    df1=df1.reshape(1,-1)
    result=lg.predict(df1)
    return result[0]

In [34]:

result=predictive(gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,Contract,TotalCharges)
if result==1:
    print("churn")
else:
    print("not churn")

not churn


In [35]:
result

0